# Generated by Django 4.1.7 on 2023-04-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0003_remove_userprofile_word_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('points', models.IntegerField(default=1)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CulturalKnowledge',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='translation',
            new_name='additionalContent',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='translation',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='grammar',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='explanationTranslation',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='sentences',
            field=models.ManyToManyField(to='mayslearning.sentence'),
        ),
    ]
