# Generated by Django 4.1.7 on 2023-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0005_quizrecord_wisewords_delete_quiz_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='wordRelated',
            field=models.ManyToManyField(null=True, to='mayslearning.word'),
        ),
    ]
