# Generated by Django 4.1.7 on 2023-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0006_sentence_wordrelated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=512, null=True)),
                ('explanationTranslation', models.CharField(blank=True, max_length=512, null=True)),
                ('wordClass', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='word',
            old_name='explanationTranslation',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='sentences',
            new_name='sentenceRelated',
        ),
        migrations.RemoveField(
            model_name='word',
            name='wordClass',
        ),
        migrations.RemoveField(
            model_name='word',
            name='explanation',
        ),
        migrations.AddField(
            model_name='word',
            name='explanation',
            field=models.ManyToManyField(null=True, to='mayslearning.explanation'),
        ),
    ]
