# Generated by Django 4.1.7 on 2023-04-23 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0007_explanation_rename_explanationtranslation_word_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficultyLevel',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('pro', 'Professional')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('fill_in', 'Fill-in-the-blank'), ('short_answer', 'Short Answer'), ('dictation', 'Dictation')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='skillType',
            field=models.CharField(choices=[('listening', 'Listening'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
