# Generated by Django 4.1.7 on 2023-04-24 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0008_question_difficultylevel_question_questiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='mayslearning.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('score', models.IntegerField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='mayslearning.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(null=True)),
                ('user_answer', models.CharField(blank=True, max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_records', to='mayslearning.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='sentenceRelated',
        ),
        migrations.AddField(
            model_name='word',
            name='explanations',
            field=models.ManyToManyField(blank=True, to='mayslearning.explanation'),
        ),
        migrations.AddField(
            model_name='word',
            name='sentences',
            field=models.ManyToManyField(blank=True, to='mayslearning.sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='wordRelated',
            field=models.ManyToManyField(blank=True, to='mayslearning.word'),
        ),
        migrations.DeleteModel(
            name='QuizRecord',
        ),
        migrations.AddField(
            model_name='examanswerrecord',
            name='exam_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='mayslearning.examrecord'),
        ),
        migrations.AddField(
            model_name='examanswerrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='mayslearning.question'),
        ),
    ]
