# Generated by Django 4.1.7 on 2023-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedaudios',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
