# Generated by Django 4.1.7 on 2023-04-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0011_relatedaudios_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAAudios',
        ),
    ]
