# Generated by Django 4.1.7 on 2023-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0012_delete_ipaaudios'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedaudios',
            name='ATag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
