# Generated by Django 4.1.7 on 2023-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0014_alter_relatedaudios_atag'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedaudios',
            name='theIPA',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
