# Generated by Django 4.1.7 on 2023-05-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0015_relatedaudios_theipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userID',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='examanswerrecord',
            name='exam_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayslearning.examrecord'),
        ),
        migrations.AlterField(
            model_name='examanswerrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayslearning.question'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theFeedback', models.TextField()),
                ('theResponse', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayslearning.userprofile')),
            ],
        ),
    ]
