# Generated by Django 4.1.7 on 2023-05-11 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0016_userprofile_birthdate_userprofile_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='sentences',
        ),
        migrations.AddField(
            model_name='explanation',
            name='sentences',
            field=models.ManyToManyField(blank=True, to='mayslearning.sentence'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='word',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='questionanswerrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='explanations',
            field=models.ManyToManyField(blank=True, related_name='related_words', to='mayslearning.explanation'),
        ),
    ]
