# Generated by Django 4.1.7 on 2023-05-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0018_word_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioFile', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='audioFile',
        ),
        migrations.AlterField(
            model_name='word',
            name='explanations',
            field=models.ManyToManyField(blank=True, related_name='words', to='mayslearning.explanation'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theSentence', to='mayslearning.audiofile'),
        ),
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='mayslearning.audiofile'),
        ),
    ]
