# Generated by Django 4.1.7 on 2023-05-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0021_alter_sentence_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='mayslearning.audiofile'),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='mayslearning.audiofile'),
        ),
    ]
