# Generated by Django 4.1.7 on 2023-05-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0022_alter_sentence_audio_alter_word_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='word',
        ),
    ]
