# Generated by Django 4.1.7 on 2023-05-12 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0024_note_rename_relatedaudios_pronunciationpart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='questionanswerrecord',
            name='examRecord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_records', to='mayslearning.examrecord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExamAnswerRecord',
        ),
    ]
