# Generated by Django 4.1.7 on 2023-05-12 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0025_rename_student_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='examrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
