# Generated by Django 4.1.7 on 2023-05-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0026_remove_questionanswerrecord_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='timestamp',
        ),
    ]
