# Generated by Django 4.1.7 on 2023-05-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0027_remove_examrecord_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='score',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='start_time',
        ),
    ]
