# Generated by Django 4.1.7 on 2023-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0028_remove_examrecord_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerrecord',
            name='examRecord',
        ),
        migrations.RemoveField(
            model_name='questionanswerrecord',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='questionanswerrecord',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswerrecord',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='examrecord',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
