# Generated by Django 4.1.7 on 2023-05-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0030_examrecord_end_time_examrecord_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerrecord',
            name='examRecord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_records', to='mayslearning.examrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswerrecord',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='questionanswerrecord',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_records', to='mayslearning.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswerrecord',
            name='user_answer',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
