# Generated by Django 4.1.7 on 2023-05-13 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0032_rename_thefeedback_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('grammar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.grammar')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.word')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyRecords',
        ),
    ]
