# Generated by Django 4.1.7 on 2023-05-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0033_studyrecord_delete_studyrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='mayslearning.audiofile'),
        ),
        migrations.AlterField(
            model_name='word',
            name='explanations',
            field=models.ManyToManyField(null=True, related_name='words', to='mayslearning.explanation'),
        ),
        migrations.AlterField(
            model_name='word',
            name='grammar',
            field=models.ManyToManyField(null=True, related_name='words', to='mayslearning.grammar'),
        ),
        migrations.AlterField(
            model_name='word',
            name='notes',
            field=models.ManyToManyField(null=True, related_name='words', to='mayslearning.note'),
        ),
    ]
