# Generated by Django 4.1.7 on 2023-05-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0035_grammar_user_note_user_question_user_sentence_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammar',
            old_name='content',
            new_name='grammar',
        ),
    ]
