# Generated by Django 4.1.7 on 2023-05-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0037_alter_word_audio_alter_word_explanations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='extraNote',
            new_name='explanation',
        ),
    ]
