# Generated by Django 4.1.7 on 2023-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0038_rename_extranote_note_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='partOfSpeech',
            field=models.CharField(blank=True, choices=[('n', 'noun'), ('pron', 'pronoun'), ('adj', 'adjective'), ('v', 'verb'), ('adv', 'adverb'), ('prep', 'preposition'), ('conj', 'conjunction'), ('art', 'article'), ('inter', 'interjection')], max_length=18, null=True),
        ),
    ]
