# Generated by Django 4.1.7 on 2023-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0039_alter_explanation_partofspeech'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='mistakes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
