# Generated by Django 4.1.7 on 2023-05-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0040_studyrecord_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='testsTotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
