# Generated by Django 4.1.7 on 2023-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0042_alter_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_random',
            field=models.BooleanField(default=True),
        ),
    ]
