# Generated by Django 4.1.7 on 2023-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0048_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciationpart',
            name='audioFile',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
