# Generated by Django 4.1.7 on 2023-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0049_alter_pronunciationpart_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciationpart',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
