# Generated by Django 4.1.7 on 2023-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0051_alter_pronunciationpart_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciationpart',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
