# Generated by Django 4.1.7 on 2023-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0052_alter_pronunciationpart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, related_name='sentences', to='mayslearning.note'),
        ),
    ]
