# Generated by Django 4.1.7 on 2023-05-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0054_remove_sentence_notes_sentence_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='notes',
            new_name='note',
        ),
    ]
