# Generated by Django 4.1.7 on 2023-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0055_rename_notes_sentence_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammar',
            old_name='explanation',
            new_name='note',
        ),
        migrations.AddField(
            model_name='grammar',
            name='sentences',
            field=models.ManyToManyField(blank=True, null=True, to='mayslearning.sentence'),
        ),
    ]
