# Generated by Django 4.1.7 on 2023-05-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0056_rename_explanation_grammar_note_grammar_sentences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprofile',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='mistakes',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='testsTotal',
        ),
    ]
