# Generated by Django 4.1.7 on 2023-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0057_remove_studyprofile_grades_remove_studyrecord_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprofile',
            name='growthIndex',
            field=models.IntegerField(default=0),
        ),
    ]
