# Generated by Django 4.1.7 on 2023-05-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0058_studyprofile_growthindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='grammar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.grammar'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.sentence'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.word'),
        ),
    ]
