# Generated by Django 4.1.7 on 2023-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0060_askquestion_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisewords',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
