# Generated by Django 4.1.7 on 2023-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0061_wisewords_title_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisewords',
            name='title',
        ),
        migrations.AddField(
            model_name='wisewords',
            name='translation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
