# Generated by Django 4.1.7 on 2023-06-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0064_alter_focalitems_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FocalItems',
            new_name='FocalItem',
        ),
    ]
