# Generated by Django 4.1.7 on 2023-06-02 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0065_rename_focalitems_focalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswerrecord',
            name='examRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_records', to='mayslearning.examrecord'),
        ),
    ]
