# Generated by Django 4.1.7 on 2023-06-03 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0066_questionanswerrecord_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='userQuestion',
        ),
        migrations.AddField(
            model_name='askquestion',
            name='likes',
            field=models.ManyToManyField(related_name='liked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
