# Generated by Django 4.1.7 on 2023-06-03 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0067_rename_question_comment_userquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
