# Generated by Django 4.1.7 on 2023-06-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0068_alter_askquestion_likes_alter_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userQuestion',
        ),
        migrations.AddField(
            model_name='askquestion',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mayslearning.comment'),
        ),
        migrations.AlterField(
            model_name='askquestion',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
