# Generated by Django 4.1.7 on 2023-06-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0069_remove_comment_userquestion_askquestion_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='mayslearning.comment'),
        ),
    ]
