# Generated by Django 4.1.7 on 2023-06-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0070_alter_askquestion_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askquestion',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='userQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mayslearning.askquestion'),
        ),
    ]
