# Generated by Django 4.1.7 on 2023-06-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0071_remove_askquestion_comments_comment_userquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userQuestion',
            new_name='question',
        ),
    ]
