# Generated by Django 4.1.7 on 2023-06-04 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0072_rename_userquestion_comment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.AddField(
            model_name='askquestion',
            name='comments',
            field=models.ManyToManyField(related_name='user_question', to='mayslearning.comment'),
        ),
        migrations.AlterField(
            model_name='askquestion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
