# Generated by Django 4.1.7 on 2023-06-05 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0073_remove_comment_question_askquestion_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='mayslearning.askquestion'),
        ),
        migrations.AlterField(
            model_name='askquestion',
            name='comments',
            field=models.ManyToManyField(related_name='question_set', to='mayslearning.comment'),
        ),
    ]
