# Generated by Django 4.1.7 on 2023-06-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0078_userpost_remove_comment_question_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mayslearning.userpost'),
        ),
    ]
