# Generated by Django 4.1.7 on 2023-06-11 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0079_userpost_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='status',
        ),
        migrations.AddField(
            model_name='userpost',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
