# Generated by Django 4.1.7 on 2023-07-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0080_remove_userpost_status_userpost_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='mayslearning.imagefile'),
        ),
    ]
