# Generated by Django 4.1.7 on 2023-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0081_sentence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
