# Generated by Django 4.1.7 on 2023-07-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0082_alter_userpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
