# Generated by Django 4.1.7 on 2023-07-13 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0083_alter_userpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
