# Generated by Django 4.1.7 on 2023-07-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0084_alter_userpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='timestamp',
        ),
    ]
