# Generated by Django 4.1.7 on 2023-07-13 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0085_remove_userpost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
