# Generated by Django 4.1.7 on 2023-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0086_userpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
