# Generated by Django 4.1.7 on 2023-07-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0087_alter_userpost_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='timestamp',
            new_name='thetimestamp',
        ),
    ]
