# Generated by Django 4.1.7 on 2023-07-13 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0088_rename_timestamp_userpost_thetimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
