# Generated by Django 4.1.7 on 2023-07-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0089_userpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='thetimestamp',
        ),
        migrations.AlterField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
