# Generated by Django 4.1.7 on 2023-07-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0091_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='mayslearning.text'),
        ),
    ]
