# Generated by Django 4.1.7 on 2023-07-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0092_studyrecord_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='mayslearning.audiofile'),
        ),
    ]
