# Generated by Django 4.1.7 on 2023-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayslearning', '0093_alter_question_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
